server:
  port: 8080

auth:
  jwt:
    secret:    secret
    issuer:    http://example.org
    audience:  http://example.org
    clockSkew: 10    # seconds
    validFor:  86400 # seconds

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG